### ISSUE TITLE
[BUG] 使用 pnpm 安装会报若干找不到 module 的错误

### ISSUE THREAD

**Issue by WanderWang** [demosify/demosify#6]
pnpm 是 yarn 的另一个替代品，参考资料：https://segmentfault.com/a/1190000013214927

使用 pnpm 会对依赖项的 package.json 有更高的要求，如[这篇文章](https://rushjs.io/pages/maintainer/package_managers/)所说

> NPM is the only option that solves the NPM doppelgangers problem. In a complex monorepo, doppelgangers sometimes cause a lot of trouble, so PNPM has an important advantage in this regard.
> Although PNPM’s symlinking strategy correctly follows the modern NodeJS module resolution standard, many legacy packages do not, which causes compatibility problems. Teams who migrate existing projects from Yarn/NPM to PNPM often encounter “bad packages” that need workarounds or fixes. The incompatibilities generally reflect real problems with those packages: (1) forgetting to list dependencies in the package.json file, or (2) implementing homebrew module resolution without handling symlinks according to the standard. Most “bad” packages have straightforward fixes, but it may seem daunting for a small team. (The PNPM Gitter chat room is a great resource for help, though.)
> PNPM is newer and less widely used than NPM or Yarn, but it’s a solid piece of software. Microsoft uses PNPM in Rush repos with hundreds of projects and hundreds of PRs per day, and we’ve found it to be very fast and reliable.
> PNPM is currently the only option that supports the --strict-peer-dependencies protection (see "strictPeerDependencies" in rush.json).

简而言之，如果项目 A 依赖了 B ，项目 B 依赖了 C ，并且在 A 中直接指明 require('C') 这种方式会在 pnpm 中报错，正确的做法是在 A 中也要显式声明依赖 C

当我在项目中通过 pnpm 中安装 demosify 时，发现有如下依赖需要添加至package.json 中才可以顺利运行

```
  "devDependencies": {
    "@babel/core": "~7.5.5",
    "@demosify/core": "~0.2.10",
    "babel-preset-env": "~1.7.0", // 这个依赖在 yarn 中也存在同样问题
    "loader-utils": "~1.2.3",
    "sass-loader": "~7.1.0",
    "v8-compile-cache": "~2.0.3",
    "webpack": "~4.36.1"
  }
```

上述依赖应该被加入到 @demosify/core 的package.json 中

**Comment by akira-cn** [comment]
这个已修复了~
